// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $images_id_ from "./routes/images/[id].ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $Upload from "./islands/Upload.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/upload.ts": $api_upload,
    "./routes/images/[id].ts": $images_id_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/Upload.tsx": $Upload,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
